server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_config:
  - job_name: system
    static_configs:
      - targets:
        - loki
      labels:
        job: varlogs
        __path__: /var/log/*.log
